### ISSUE TITLE
Сделать для каждого блока свой миксин

### ISSUE THREAD

**Issue by Sha1fei** [Sergio-Ka/MySummary#10]
Передавать в mixin объект и использовать деструктуризацию при передаче параметров.
+header-of-block({image: "icon_2",  section: "CONTACT"})

mixin header-of-block({image, section})
	.header-of-block
		img.header-of-block__icon(src="public/images/"+image+".png")/
		.header-of-block__section
			.category-definition= section
		.header-of-block__line
			hr.line

**Comment by chmnkh** [comment]
тут еще вообще стоит пересмотреть деление на блоки и элементы, возможно где-то есть лишние блоки, вместо которых подойдет лучше элемент

**Comment by Sergio-Ka** [comment]
В рамках данного issue так же закрываются issue с номерами 14, 15, 17, 18, 19, 21

**Comment by Sha1fei** [comment]
Это ишью можешь закрыть после одобрения связанных с ним.

**Comment by chmnkh** [comment]
Закрывай тут.
