### ISSUE TITLE
Все блоки должны быть в своих папках

### ISSUE THREAD

**Issue by chmnkh** [Sergio-Ka/MySummary#14]

**Comment by chmnkh** [comment]
Нельзя определять в одних блоках другие, как например здесь:
```
mixin software-level(softwareName, softwareLevel)
    div(class="software-name")= softwareName
    div(class="software-scale")
        div(class="software-scale software-scale_num"+softwareLevel)

div(class="software")
    +header-of-block("icon-software", "software")
    div(class="software-content")
        div(class="software-content__container-1")
            +software-level("photoshop", 1)
            +software-level("illustrator", 3)
            +software-level("indesign", 5)
```

**Comment by Sergio-Ka** [comment]
выполнено в рамках issue #10

**Comment by chmnkh** [comment]
```
mixin summary()
    main.summary
        block

mixin summary-column-left()
    section.summary__column.summary__column_position_left
        block

mixin summary-column-right()
    section.summary__column.summary__column_position_right
        block
```

```
        +summary()
            +summary-column-left()
```

А почему именно так сделано? Почему summary блок не сделать просто одним миксином, как и все остальное?

**Comment by chmnkh** [comment]
Блок content-list лежит в папке content-list__item

**Comment by chmnkh** [comment]
На summary кстати внешнее позиционирование. Тоже косяк.
На content-list'е тоже. Там дефолтный маргин, не забывай о них, когда списки юзаешь.

**Comment by Sergio-Ka** [comment]
Не совсем пойму по последнему посту. У summary внешнее позиционирование потому, что это родительский элемент. Родителя с классом на нем нет, чтобы его обернуть в дочерний и через него отпозиционировать. Часть по content-list вообще не пойму. Где там какое внешнее позиционирование? Оно ведь отражено так как должно? В чем тогда проблема?

**Comment by Sergio-Ka** [comment]
Не совсем пойму по последнему посту. У summary внешнее позиционирование потому, что это родительский элемент. Родителя с классом на нем нет, чтобы его обернуть в дочерний и через него отпозиционировать. Часть по content-list вообще не пойму. Где там какое внешнее позиционирование? Оно ведь отражено так как должно? В чем тогда проблема? Остальное сделал, но пока не залил.

**Comment by Sergio-Ka** [comment]
Все таки закинул изменения не считая вопросов последнего поста.

**Comment by chmnkh** [comment]
> У summary внешнее позиционирование потому, что это родительский элемент. Родителя с классом на нем нет, чтобы его обернуть в дочерний и через него отпозиционировать. 

Ну в БЭМ нету такого понятия, как "родительский элемент", это ты его уже сам придумал :)
Зато есть понятие блок, и блок позиционировать по известным причинам нельзя.Что тебе мешает посмотреть на summary как на блок, который растягивается по ширине родителя, а его контент - центрируется по горизонтали? Что тебе мешает не блок позиционировать, а весь контент внутри блока?

> Часть по content-list вообще не пойму. Где там какое внешнее позиционирование?

ul элементы имеют дефолтный margin

> Оно ведь отражено так как должно? В чем тогда проблема? 

Проблема дефолтных маргинов на блоке ровно та же самая, что и проблема маргинов, которые бы ты руками на нем написал.

**Comment by Sergio-Ka** [comment]
Сделано. #17 по ходу закрытия этого можно будет закрыть?
