### ISSUE TITLE
Респонсив

### ISSUE THREAD

**Issue by chmnkh** [Sergio-Ka/MySummary#20]
Посмотри на страницу на разных размерах, все должно выглядеть красиво (что-то где-то отцентровать нужно будет, как пример)

**Comment by chmnkh** [comment]
Тебе не кажется, что это немного экстремально выглядит? :)
![image](https://user-images.githubusercontent.com/18498637/48391979-bb85e080-e73b-11e8-9ad9-5686aca47c07.png)

**Comment by Sergio-Ka** [comment]
Нет, не кажется. Сначала было слева у блока контактов. Вы сказали с Валентином выровнять по центру, я сделал. Я не дизайнер. Скажите как надо - переделаю. Или речь о слишком больших пробелах между блоками?

**Comment by chmnkh** [comment]
1. У профайла из-за минимальной высоты куча постого места снизу
2. Переход сильно рано сделан в одну колонку, из-за этого все вылядит не эстетично, сделай хотя бы чтобы пикселей до 900 по ширине не переходило бы в одну колноку. Можешь поиграться с фонт сайзом на html, например, раз у нас ремы.

Понимаю, что ты не дизайнер, но зачастую и на практике какие-то дизайнерские решения приходится без дизайнера принимать (я уже не говорю о случаях, когда тебе даже примерно не говорят, как это должно выглядеть, а только лишь то, что оно должно "как-то" быть), так что думать о том как что выглядит - это полезно.

**Comment by Sergio-Ka** [comment]
Сделано.
