### ISSUE TITLE
Переписать передачу параметров

### ISSUE THREAD

**Issue by chmnkh** [Sergio-Ka/MySummary#25]
```
mixin about(options)
    if (!options)
        -options = {name:"name", surname:"surname", profession:"profession"};
    -let {name="name", surname="surname", profession="profession"} = options;
```
это все можно красивее переписать, например дефолт для options прямо на уровне определения миксина написать:
```mixin about(options = {name:"name", surname:"surname", profession:"profession"})```
а деструктуризацию оставить в теле миксина, как сейчас
или можно сразу деструктуризацию параметров сделать:
```mixin about({name="name", surname="surname", profession="profession"})```
при этом в таком случае дефолт для опций ты можешь какой-то задать, или вообще пустой объект сделать, например, здесь не сильно принципиально:
```mixin about({name="name", surname="surname", profession="profession"} = {})```
```mixin about({name="name", surname="surname", profession="profession"} = defaultOptions)```

Тут на твое усмотрение как ты перепишешь, но суть в том, что можно оптимальнее написать, чем сейчас.

**Comment by Sergio-Ka** [comment]
Использовал первый метод как более оптимальный на случай вызова миксина без параметров.
