### ISSUE TITLE
Переписать ячейки в contact

### ISSUE THREAD

**Issue by chmnkh** [Sergio-Ka/MySummary#26]
У тебя не совсем грамотно сделаны классы на contact__cell:
Вся первая колонка - это по идее заголовки. Вся вторая колонка - значения. Это же разные сущности, в таблицах даже теги для этих сущностей разные. А ты им назначил один и тот же css-класс, при этом меняя заголовки модификаторами. 
Более грамотным был бы подход, при котором на этих сущностях разные классы были бы и разные стили. У тебя по сути то на элементе cell висит только display и font-size. font-size логичнее выглядит на уровне таблицы, на мой взгляд, а не отдельной ячейки. А display можно для двух классов написать один, это ничего страшного. Тогда у тебя все эти модификаторы для cell просто уйти должны, и все станет чище и логичнее.

**Comment by Sergio-Ka** [comment]
пофиксено
