### ISSUE TITLE
Называть модификаторы по смыслу

### ISSUE THREAD

**Issue by chmnkh** [Sergio-Ka/MySummary#27]
Пример плохого названия (куча подобного еще в contact, но на него отдельное ишью создано):
```
span.profile__content_font-weight_bold
```
Начнем с того, что здесь модификатор ключ-значение - это перебор и было бы достаточно булевого, потому что значение для font-weight ключа - всего одно.
Далее, не надо имя модификатора на css свойства завязывать. Выдерживай абстракцию, не тащи css правила в имена классов.  Не надо на уровне именования думать, как ты там это будешь в стилях реализовывать.
Далее, модификаторы нужно всегда стремиться по смыслу называть. Конечно, иногда модификатор тупо меняет цвет/форму/еще что-то и никакого смысла больше не несет. Но в некоторых случаях - несет. В примере выше жирный текст наверняка не жирный просто так, какой смысл в блоке, который просто рендерит сначала обычный текст, а потом жирный? Поэтому тупо назвать модификатор bold - не пойдет.
Твой же модификатор, типа
```
.skills__scale-circle_inactive
```
уже корректно назван, ты же здесь не написал ```skills__scale-circle_bg-color_grey``` или что-нибудь такое.
И кстати, хоть и ишью по модификаторам, в переменных у тебя то же самое, обрати внимание:
```
textFontWeightBold
```

**Comment by Sergio-Ka** [comment]
Пофиксено.

**Comment by chmnkh** [comment]
```
p.profile__content= text
  span.profile__content_marked= textMarked
```

 Заметил, что у тебя это вообще, оказывается, один элемент. Тут тебе нужно либо это оставить одним элементом и вынести на один уровень вложенности как-то, либо сделать толстый текст другим элементом, ибо элемент, содержащий сам себя - смысла мало имеет. Потому что получается какая-то сущность содержит саму себя, которая тоже тогда должна по идее саму себя содержать, и так мы уходим в бесконечность.

**Comment by Sergio-Ka** [comment]
Пофиксено.
