### ISSUE TITLE
Убрать дублирование в стилях

### ISSUE THREAD

**Issue by chmnkh** [Sergio-Ka/MySummary#29]
1) Селекторы. Например:
```
  &__scale
    width 20.357rem
    height 1.643rem
    background #e6e6e6
  &__scale_filled
    background #3d6cb0
```
зачем писать 2 раза scale, если можно написать:
```
  &__scale
    width 20.357rem
    height 1.643rem
    background #e6e6e6

    &_filled
        background #3d6cb0
```
Еще пример:  в content-list 2 раза написано имя блока (в начале и в конце файла). Вот это вот:
```
  &__item
    ...
  &__item-date
    ...
  &__item-second-name
    ...
  &__item-description
    ...
```
айтем везде руками тоже зачем писать? Не стесняйся амперсанд юзать активнее.

2) Дублирование свойств. Например:
```
  &__name
    line-height 3.3rem
    text-align center
    font-size 4.1rem
    text-transform uppercase
  &__surname
    text-align center
    font-size 4.5rem
    font-weight bold
    text-transform uppercase
  &__profession
    text-align center
    font-size 1.8rem
    font-weight bold
    text-transform uppercase
    margin-bottom 1rem
```
У тебя прямо много раз одно и то же написано. Text transform можно вынести с этих элементов на уровень выше, он отнаследуется. То же самое с text-align. font-weight для surname и profession можно тоже для двух селекторов сразу написать (здесь опционально, потому что профит спорный).

**Comment by Sergio-Ka** [comment]
Пофиксено, на сколько я понял второй пункт.

**Comment by chmnkh** [comment]
sumary.styl:
```
  &__column
    float left

    &_position_left
      width 30.425rem
      margin 6.5rem 5.6rem 0 4.5rem

    &_position_right
      width 46.6rem
      margin 5.5rem 0 0 0
```
имя модификатора (position) дублируется
стили, типа
```
.x
  &_имя-модификатора
       &_значение-модификатора
       &_другое-значение-модификатора
```
это классика для ключ-значение модификаторов, лучше сразу так везде привыкать писать

это поправишь и можешь сам ишью закрыть

**Comment by Sergio-Ka** [comment]
Пофиксено.

**Comment by Sergio-Ka** [comment]
Сделал.
