### ISSUE TITLE
Readme

### ISSUE THREAD

**Issue by Sha1fei** [Sergio-Ka/MySummary#7]
Добавить в README описание проекта и команды его запуска.

**Comment by Sergio-Ka** [comment]
Пофиксил в рамках issue #1 добавил команды запуска в readme.md. Изменения пока не смерджены, так как issue#1 не одобрен и находятся в ветке 1-fix-readme-package.json

**Comment by Sergio-Ka** [comment]
изменения смерджены в ветку рефактор

**Comment by Sergio-Ka** [comment]
Вроде как давно пофиксено, и минификатор стоит и команда на клонирование добавлена. Можно закрывать?

**Comment by Sha1fei** [comment]
Да
